[package]
name = "clevis"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

[lib]
name = "clevis"
path = "src/lib.rs"

[[bin]]
name = "clevis"
path = "src/main.rs"

[dependencies]
base64 = "0.21.0"
clap = { version = "4.2.1", features = ["derive"] }
env_logger = "0.10.0"
josekit = "0.8.2"
log = "0.4.20"
serde = "1.0.160"
sha2 = "0.10.6"
serde_json = { version = "1.0.95", features = ["preserve_order"] }
ureq = { version = "2.6.2", features = ["json"] }
sha1 = "0.10.6"
# vsss-rs = "2.7.1"

[features]
_backend = []
